# Generated by Django 5.2.5 on 2025-08-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
